const stages=[
 ['LOCAL PROPORTION-SUPERVISED LEARNING','Learn from bags, locally.','Each client optimizes a bag-level proportion objective. Its model updates and bag-proportion information support cross-client collaboration.','Local bags → DLLP training → Model updates','Instance labels are not used as training supervision.'],
 ['CLIENT-LEVEL COLLABORATION','Find the right collaboration context.','Compare bag-proportion sets, select the top H compatible peers, and weight their models by compatibility and sample count.','Bag proportions → Compatibility → Base aggregation','Self-contribution is retained in the compatibility-guided base.'],
 ['CLASS-WISE EVIDENCE','Identify what each peer can contribute.','Measure whether a source offers greater class coverage than the target, and whether its predicted proportions agree with its own observed bag proportions.','Complementarity = Coverage gain × Reliability','Reliability is recomputed after local training in every communication round. It is a proportion-consistency proxy, not instance-level accuracy.'],
 ['CONSERVATIVE REFINEMENT','Refine class contributions.','Cap complementarity scores and mix class-wise collaborator weights with the base weights. Apply the refinement only to classifier rows and biases.','Refined weights = (1 − η) α + η β','Non-classifier parameters use the compatibility-guided aggregation. Without positive complementary evidence, classifier weights also fall back to the base.']
];
function setStage(i){const s=stages[i]; const picture=document.getElementById('stage-image'); picture.src='assets/method-panel-'+(i+1)+'-0924.png';picture.style.width='100%';picture.style.marginLeft='0';picture.alt=s[1];document.querySelector('.method-explorer').dataset.stage=i;['step-kicker','step-title','step-description','step-equation','step-note'].forEach((id,j)=>document.getElementById(id).textContent=s[j]);document.querySelectorAll('[data-step]').forEach(b=>{const active=Number(b.dataset.step)===i;b.classList.toggle('active',active);b.setAttribute('aria-pressed',String(active));});}
document.querySelectorAll('[data-step]').forEach(b=>b.addEventListener('click',()=>setStage(Number(b.dataset.step))));setStage(0);
// Supplied manuscript draft, Table 1. Values are transcribed, not generated.
const methods=['DLLP','PVC','LLP-DC','FedProx','FedWMSAM','FedDyn','Ditto','FEROMA','pFedGraph','FedC²'];
const datasets=[
 {name:'CIFAR-10',values:[[13.96,12.33,11.58],[10,10,10],[10,10,10],[14.83,13.38,11.63],[10.80,10,13.14],[12.60,13.28,12.09],[12.22,10.55,10.85],[11.49,11.88,10.98],[11.78,10.02,11.99],[21.71,17.56,13.16]],note:'FedC² achieves the highest reported accuracy at all three heterogeneity levels.'},
 {name:'SVHN',values:[[19.59,19.59,19.52],[19.59,19.59,19.59],[19.59,19.59,19.59],[19.59,19.41,18.07],[19.59,19.58,19.55],[18.57,19.59,24.31],[16.49,16.25,16.55],[18.67,19.59,19.52],[11.04,9.68,9.57],[21.82,19.81,17.18]],note:'FedC² leads at β = 0.25 and 0.50; FedDyn leads at β = 0.75.'},
 {name:'Fashion-MNIST',values:[[55.75,52.51,62.62],[11.56,10,11.62],[10,10,10],[57.30,56.07,60.72],[17.66,21.19,22.39],[50.27,48.70,55.29],[55.76,52.50,62.66],[12.55,9.39,11.54],[11,19.68,16.34],[71.05,67.56,66.24]],note:'FedC² achieves the highest reported accuracy at all three heterogeneity levels.'},
 {name:'Mini-ImageNet',values:[[30.24,31.81,32.41],[22.56,24.25,22.52],[25.47,27.34,27.55],[30.36,31.43,32.49],[31.69,30.88,30.46],[28.04,27.67,27.40],[30.10,31.65,32.14],[29.86,30.43,29.55],[32.54,32.17,31.35],[30.91,32.60,32.75]],note:'FedC² leads at β = 0.50 and 0.75; pFedGraph leads at β = 0.25. The class-disjoint evaluation protocol needs clarification before publication.'}
];
const tabs=document.querySelector('.dataset-tabs');datasets.forEach((d,i)=>{const b=document.createElement('button');b.textContent=d.name;b.addEventListener('click',()=>setDataset(i));tabs.append(b);});
function setDataset(i){const d=datasets[i];document.getElementById('dataset-title').textContent=d.name;document.getElementById('dataset-note').textContent=d.note;const best=[0,1,2].map(k=>Math.max(...d.values.map(r=>r[k])));const second=[0,1,2].map(k=>[...new Set(d.values.map(r=>r[k]))].sort((a,b)=>b-a)[1]);document.getElementById('result-rows').innerHTML=d.values.map((r,j)=>`<tr class="${j===9?'ours':''}"><th scope="row">${methods[j]}</th>${r.map((v,k)=>`<td class="${v===best[k]?'best':v===second[k]?'second':''}">${v.toFixed(2)}</td>`).join('')}</tr>`).join('');[...tabs.children].forEach((b,j)=>{b.classList.toggle('active',j===i);b.setAttribute('aria-pressed',String(j===i));});renderBars(i);}setDataset(0);

function renderBars(i){const d=datasets[i];document.querySelector('#beta-select').dataset.active=i;const k=Number(document.querySelector('#beta-select').value);const ours=d.values[9][k];const leaders=d.values.slice(0,9).map((r,j)=>({name:methods[j],value:r[k]})).sort((a,b)=>b.value-a.value).slice(0,2);const selected=[{name:'FedC²',value:ours,label:'OUR METHOD'},...leaders.map((row,j)=>({...row,label:j===0?'STRONGEST COMPARISON':'NEXT COMPARISON'}))];document.querySelector('#comparison-bars').innerHTML=selected.map((row,j)=>`<article class="leader-card ${j===0?'our-leader':''}"><span>${row.label}</span><strong>${row.value.toFixed(2)}%</strong><b>${row.name}</b></article>`).join('');const delta=ours-leaders[0].value;document.querySelector('#selected-acc').textContent=ours.toFixed(2)+'%';document.querySelector('#selected-comparison').textContent=`${Math.abs(delta).toFixed(2)} percentage points ${delta>=0?'above':'below'} the strongest comparison method in this setting.`;}
document.querySelector('#beta-select').addEventListener('change',e=>renderBars(Number(e.target.dataset.active)));
const scalePlots={rounds:{src:'assets/exp-rounds.png',alt:'Reported accuracy across communication rounds for four datasets',caption:'Reported accuracy across communication rounds, from manuscript Figure 2.',label:'Enlarge communication rounds plot'},clients:{src:'assets/exp-clients.png',alt:'Reported accuracy across the number of clients for four datasets',caption:'Reported accuracy across client counts, from manuscript Figure 2.',label:'Enlarge client count plot'}};
document.querySelectorAll('[data-scale-plot]').forEach(button=>button.addEventListener('click',()=>{const key=button.dataset.scalePlot;const plot=scalePlots[key];const image=document.querySelector('#scale-plot');const opener=image.closest('.image-open');image.src=plot.src;image.alt=plot.alt;opener.dataset.image=plot.src;opener.dataset.caption=plot.caption;opener.setAttribute('aria-label',plot.label);document.querySelectorAll('[data-scale-plot]').forEach(item=>{const active=item===button;item.classList.toggle('active',active);item.setAttribute('aria-pressed',String(active));});}));
const dialog=document.querySelector('#figure-dialog');document.querySelectorAll('.image-open').forEach(button=>button.addEventListener('click',()=>{document.querySelector('#dialog-image').src=button.dataset.image;document.querySelector('#dialog-image').alt=button.dataset.caption;document.querySelector('#dialog-caption').textContent=button.dataset.caption;document.querySelector(".dialog-image-scroll").classList.remove("original-size");document.querySelector("#figure-size").textContent="Original size";dialog.showModal();}));document.querySelector('#close-figure').addEventListener('click',()=>dialog.close());dialog.addEventListener('click',e=>{if(e.target===dialog)dialog.close();});

document.querySelector("#figure-size").addEventListener("click",e=>{const original=document.querySelector(".dialog-image-scroll").classList.toggle("original-size");e.target.textContent=original?"Fit to screen":"Original size";});
